// Scholarly transliterations of the 114 surah names (index 0 = surah 1).
// Uses ʾ (U+02BE) for hamza, ʿ (U+02BF) for ayn, macrons and dotted letters.
export const SURAH_NAMES = [
  'Al-Fātiḥah',
  'Al-Baqarah',
  'Āl ʿImrān',
  'An-Nisāʾ',
  'Al-Māʾidah',
  'Al-Anʿām',
  'Al-Aʿrāf',
  'Al-Anfāl',
  'At-Tawbah',
  'Yūnus',
  'Hūd',
  'Yūsuf',
  'Ar-Raʿd',
  'Ibrāhīm',
  'Al-Ḥijr',
  'An-Naḥl',
  'Al-Isrāʾ',
  'Al-Kahf',
  'Maryam',
  'Ṭā-Hā',
  'Al-Anbiyāʾ',
  'Al-Ḥajj',
  'Al-Muʾminūn',
  'An-Nūr',
  'Al-Furqān',
  'Ash-Shuʿarāʾ',
  'An-Naml',
  'Al-Qaṣaṣ',
  'Al-ʿAnkabūt',
  'Ar-Rūm',
  'Luqmān',
  'As-Sajdah',
  'Al-Aḥzāb',
  'Sabaʾ',
  'Fāṭir',
  'Yā-Sīn',
  'Aṣ-Ṣāffāt',
  'Ṣād',
  'Az-Zumar',
  'Ghāfir',
  'Fuṣṣilat',
  'Ash-Shūrā',
  'Az-Zukhruf',
  'Ad-Dukhān',
  'Al-Jāthiyah',
  'Al-Aḥqāf',
  'Muḥammad',
  'Al-Fatḥ',
  'Al-Ḥujurāt',
  'Qāf',
  'Adh-Dhāriyāt',
  'Aṭ-Ṭūr',
  'An-Najm',
  'Al-Qamar',
  'Ar-Raḥmān',
  'Al-Wāqiʿah',
  'Al-Ḥadīd',
  'Al-Mujādilah',
  'Al-Ḥashr',
  'Al-Mumtaḥanah',
  'Aṣ-Ṣaff',
  'Al-Jumuʿah',
  'Al-Munāfiqūn',
  'At-Taghābun',
  'Aṭ-Ṭalāq',
  'At-Taḥrīm',
  'Al-Mulk',
  'Al-Qalam',
  'Al-Ḥāqqah',
  'Al-Maʿārij',
  'Nūḥ',
  'Al-Jinn',
  'Al-Muzzammil',
  'Al-Muddaththir',
  'Al-Qiyāmah',
  'Al-Insān',
  'Al-Mursalāt',
  'An-Nabaʾ',
  'An-Nāziʿāt',
  'ʿAbasa',
  'At-Takwīr',
  'Al-Infiṭār',
  'Al-Muṭaffifīn',
  'Al-Inshiqāq',
  'Al-Burūj',
  'Aṭ-Ṭāriq',
  'Al-Aʿlā',
  'Al-Ghāshiyah',
  'Al-Fajr',
  'Al-Balad',
  'Ash-Shams',
  'Al-Layl',
  'Aḍ-Ḍuḥā',
  'Ash-Sharḥ',
  'At-Tīn',
  'Al-ʿAlaq',
  'Al-Qadr',
  'Al-Bayyinah',
  'Az-Zalzalah',
  'Al-ʿĀdiyāt',
  'Al-Qāriʿah',
  'At-Takāthur',
  'Al-ʿAṣr',
  'Al-Humazah',
  'Al-Fīl',
  'Quraysh',
  'Al-Māʿūn',
  'Al-Kawthar',
  'Al-Kāfirūn',
  'An-Naṣr',
  'Al-Masad',
  'Al-Ikhlāṣ',
  'Al-Falaq',
  'An-Nās',
]

// Fuzzy key for latin search. Callers match with:
//   normalizeName(name).includes(normalizeName(query))
export function normalizeName(s) {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '') // strip macrons / dots
    .replace(/[ʾʿʻ‘’'`]/g, '') // hamza, ayn, apostrophes
    .replace(/[\s-]/g, '')
    .replace(/^al/, '')
    .replace(/ee/g, 'i')
    .replace(/oo/g, 'u')
    .replace(/(.)\1+/g, '$1') // collapse doubled letters
    .replace(/ah$/, 'a') // fatihah ~ fatiha (but keep nuh, sharh)
}
